services:
  - type: web
    name: langflow-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: LANGFLOW_API_KEY
        value: sk-s7MVeXQ4hXxG4kSkrV72eQgjIQXc8KSAPgcYBWn6DWg
